### ISSUE TITLE
clio not working completely right

### ISSUE THREAD

**Issue by cathylbh** [Academy-Creatio/StudioDevMay#1]
I am still having some issues with clio.  I can register an app and I can do an init for a package, but I cannot list packages.  Here is what I get.  Do you have any ideas?
![image](https://user-images.githubusercontent.com/29264562/118710608-c376dd80-b7db-11eb-9349-b8eea8958e46.png)

**Comment by kirillkrylov** [comment]
You have to install gate before running packages command. 

To test Clio run 
```ps
clio ping
```
if success then install gate by executing. Install gate install cliogate packages that extends API necessary to leverage other clio commands.
```ps
clio install-gate
```



after cliogate is installed you can execute 
```ps
clio packages
```

**Comment by cathylbh** [comment]
This is the result:
![image](https://user-images.githubusercontent.com/29264562/118821499-89a5e580-b874-11eb-8ee0-b842f0bcb6cc.png)

**Comment by kirillkrylov** [comment]
After installing a package, restart your app with
```ps
clio restart
```
